[package]
name = "zeph"
version = "0.3.1"
edition = "2021"
description = "A CLI tool for inspecting zarr data stores"
license = "MIT"
repository = "https://github.com/tomwetherell/zeph"

[dependencies]
async-trait = "0.1"
bytes = "1"
crossterm = "0.28"
futures = "0.3"
clap = { version = "4", features = ["derive"] }
anyhow = "1"
chrono = { version = "0.4", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
object_store = { version = "0.13", features = ["aws", "gcp", "azure", "http"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
tokio = { version = "1", features = ["rt-multi-thread"] }
url = "2"
zarrs = { version = "0.23", features = ["async"] }
zarrs_object_store = "0.6"
zarrs_storage = "0.4"

[dev-dependencies]
tempfile = "3"

[profile.dist]
inherits = "release"
lto = "thin"
